### ISSUE TITLE
Flatpak, Appimage releases

### ISSUE THREAD

**Issue by Soundtoxin** [TeamForbiddenLLC/warfork-qfusion#256]
Have you considered supplying a flatpak or appimage for users who don't want to use Steam to play? A distro package would usually be ideal, but it looks like pretty much only Arch (via the AUR) has packaged Warfork so far. Not even nixpkgs has a Warfork package yet (though I see that one has been requested). Flatpak seems like a nice fallback for users on distros without a package yet, or in cases where the distro package falls a bit behind.

**Comment by Warfork** [comment]
> Have you considered supplying a flatpak or appimage for users who don't want to use Steam to play? A distro package would usually be ideal, but it looks like pretty much only Arch (via the AUR) has packaged Warfork so far. Not even nixpkgs has a Warfork package yet (though I see that one has been requested). Flatpak seems like a nice fallback for users on distros without a package yet, or in cases where the distro package falls a bit behind.

Hey there,

Steam has always been our focal point and I don't foresee this happening anytime soon. I really appreciate you opening this issue on GitHub and caring about the game. You can however use steamcmd to download the game anonymously by performing the following steps:

> sudo apt-get install steamcmd
> run steamcmd
> force_install_dir typeyourpathhere
> login anonymous
> app_update 1136510

I hope this helps and you're always welcome to join our discord: https://warfork.com/discord

**Comment by Soundtoxin** [comment]
Steam and Discord are both proprietary, so unfortunately this does not help. I wanted to use and support Warfork since it seemed like the modern and maintained version of the game, but if non-Steam users are second-class citizens and you're building a community around Discord of all things, perhaps I should go with Warsow after all.

**Comment by Warfork** [comment]
> Steam and Discord are both proprietary, so unfortunately this does not help. I wanted to use and support Warfork since it seemed like the modern and maintained version of the game, but if non-Steam users are second-class citizens and you're building a community around Discord of all things, perhaps I should go with Warsow after all.

I'm sorry Warfork doesn't suit your needs and expectations. Just so you're aware Warfork and Warsow both contain proprietary assets, so these might be projects you should avoid. I wish you well and hope you have a happy new year. You're always welcome to reach out to us.

**Comment by Warfork** [comment]
@Soundtoxin I forgot to plug our friends over at Xonotic. You might want to check out their game:

https://xonotic.org/
https://xonotic.org/chat/

**Comment by Gelmo** [comment]
@Soundtoxin Just a quick heads up, Warsow's community is also based in Discord, and Warsow also uses proprietary assets. From an OSS perspective, Warsow and Warfork are equally (non-)free. And since the contributions list in Warfork is actually up to date, it's fair to say that Warfork is more in line with licenses distributed with the game. In regard to non-Steam users being treated as second-class citizens, you should see how people are treated in the Warsow discord server.

If you have any questions about packaging Warfork or Warsow for your distro of choice, let me know or refer to my PKGBUILD in the AUR.

FWIW, even Xonotic, which historically had its community on IRC, has since moved to Discord (despite having a bridge set up for people that don't want to use Discord). Warfork is a game, and gaming communities tend to exist on Discord these days. An IRC server, Mastodon instance, Matrix, etc is fantastic for a dev community, but it's useless for the general user who just wants to ask for help or talk to their friends that also play the game. These people don't exist in those other communities/protocols. I'm not trying to say that you're "wrong" for not wanting to use Discord, rather, that the Warfork team isn't "wrong" for choosing to use Discord as their community hub. That's just how things go in 2024.
