### ISSUE TITLE
Inconsistency between unmute and removemute

### ISSUE THREAD

**Issue by Gauley123** [TeamForbiddenLLC/warfork-qfusion#341]
command is called removemute and the callvote is unmute, add alias for unmute (and unban aswell)

**Comment by CoolElectronics** [comment]
it was called unmute from the beginning and the listip system uses `addip`/`removeip` prefixes so if the command was named `unmute` it would be inconsistent with that... and i can't rename the callvote or `removeip` because it would break old configs

i believe the current inconsistency is the lesser of evils
