### ISSUE TITLE
Add racemod to Warfork

### ISSUE THREAD

**Issue by Warfork** [TeamForbiddenLLC/warfork-qfusion#76]
Unless @msc#3261 volunteers this will probably never get done :) some sort of Steam leaderboard implementation would be great too

https://github.com/DenMSC/wsw-race/tree/racemod

**Comment by Warfork** [comment]
Correct repo: https://github.com/hettoo/wsw-race/tree/racemod

**Comment by Warfork** [comment]
> hettoo — 
> but also main question is what to do with weapon modifications etc
> racemod has some little differences in reload times and other things

Would need to investigate how to handle this.

**Comment by hettoo** [comment]
I think there are 3 stages to this:
1. Make sure the current gametype script is compatible with Warfork, which I think is mainly adding prejump checking.
2. Add further features and fixes that would benefit or at least not hurt Warfork anyway.
3. Figure out how to integrate more obtrusive changes, such as indeed alternative weapon definitions.

I think the weapon defs could be put behind a gametype configuration switch that's off by default.

The first two steps should be relatively straightforward, and that's something already even if number 3 gives trouble.

**Comment by Warfork** [comment]
@hettoo Steam Leaderboard Docs: https://partner.steamgames.com/doc/features/leaderboards/guide 

It seems you can create Leaderboards through Steamworks API, which is great. I'm curious what the limitations of this are though, because thousands of race maps exist IIRC.

**Comment by Gelmo** [comment]
> Correct repo: [hettoo/wsw-race@`racemod`](https://github.com/hettoo/wsw-race/tree/racemod?rgh-link-date=2022-02-27T17%3A19%3A04Z)

That's hrace, the gametype, not racemod. Racemod:

https://github.com/DenMSC/racemod_2.1

Racemod assets:

https://github.com/DenMSC/racemod_data

Challenges:
- Extra set of weapon defs. Usage would need to be based on a cvar, like g_racemod 1
- Should be based on cvar instead of gametype so it can be used in other gametypes
- Textures/pk3s should still be separate, like they are now with the mod implementation, since the used texture packs override some of the default textures. I think some sounds are overridden as well.
- Support for a separate config is necessary, and the client would need to switch between configs based on the setting of g_racemod
- Support for a third HUD type is necessary; Game, Spec, Race
